sudo: false
language: node_js
node_js:
  - "8"
services:
  - postgresql
branches:
  only:
    - master
cache:
  directories:
    - node_modules
before_script:
  - psql -c 'create database grapqhldbtest;' -U postgres
  - root
before_install:
  - npm update
  - sudo apt-get update
  - sudo apt-get install language-pack-es
  - sudo /etc/init.d/postgresql stop
  - sudo /etc/init.d/postgresql start 9.3
install:
  - npm install
script:
  - npm test
  - npm run coveralls
addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
env:
  global:
    - PGPORT=5432
